#!/usr/bin/env python3
"""Render the Lunchpad logo for the Launchkey MK4's screen: 128 x 64 pixels, one bit
each, 19 SysEx bytes per row (7 pixels per byte, highest bit leftmost, five spare bits
in the last byte). Writes src-tauri/src/midi/models/launchkey_screen.rs and a preview
PNG next to this script's output for a look. Run from the project root."""
from PIL import Image, ImageDraw, ImageFont

SRC = ".github/logo.png"
OUT = "src-tauri/src/midi/models/launchkey_screen.rs"
PREVIEW = "/tmp/launchkey-screen-preview.png"
W, H = 128, 64

# The logo, drawn rather than resampled: four lit tiles with the words cut out of them
# in the same places as in colour, which stays legible at 64 pixels. The wordmark
# beside it takes the largest size that fits the rest of the screen.
screen = Image.new("1", (W, H), 0)
draw = ImageDraw.Draw(screen)
try:
    def font(size):
        return ImageFont.load_default(size=size)
except TypeError:  # older Pillow without a scalable default
    def font(size):
        return ImageFont.load_default()

TILE, GAP, LEFT, TOP = 28, 4, 2, 2
for row in range(2):
    for col in range(2):
        x0 = LEFT + col * (TILE + GAP)
        y0 = TOP + row * (TILE + GAP)
        draw.rounded_rectangle((x0, y0, x0 + TILE - 1, y0 + TILE - 1), radius=5, fill=1)
logo_w = 2 * TILE + GAP
def centred_dark(text, size, y):
    f = font(size)
    l, t, r, b = draw.textbbox((0, 0), text, font=f)
    x = LEFT + (logo_w - (r - l)) // 2 - l
    draw.text((x, y - t), text, fill=0, font=f, stroke_width=1, stroke_fill=0)
centred_dark("LUNCH", 17, TOP + 9)
centred_dark("PAD", 17, TOP + TILE + GAP + 9)

right_x = LEFT + logo_w + 8
avail = W - right_x - 2
size = 24
while size > 8:
    f = font(size)
    l, t, r, b = draw.textbbox((0, 0), "Lunch", font=f)
    if r - l <= avail:
        break
    size -= 1
f = font(size)
l, t, r, b = draw.textbbox((0, 0), "Lunch", font=f)
line_h = b - t
block_h = 2 * line_h + 2
y = (H - block_h) // 2
draw.text((right_x - l, y - t), "Lunch", fill=1, font=f)
draw.text((right_x - l, y + line_h + 2 - t), "pad", fill=1, font=f)

rows = []
for y in range(H):
    row = []
    for byte in range(19):
        value = 0
        for bit in range(7):
            x = byte * 7 + bit
            lit = x < W and screen.getpixel((x, y))
            value |= (1 if lit else 0) << (6 - bit)
        row.append(value)
    rows.append(row)

lines = [
    "//! The Lunchpad logo for the Launchkey MK4's screen, generated by",
    "//! `tools/generate-launchkey-screen.py` from `.github/logo.png`: 128 x 64 pixels,",
    "//! 19 SysEx data bytes per row (7 pixels each, highest bit leftmost).",
    "",
    "/// One bit per pixel, row by row, ready for the bitmap message.",
    "pub const LOGO: [u8; 1216] = [",
]
for row in rows:
    lines.append("    " + ", ".join(f"0x{b:02X}" for b in row) + ",")
lines.append("];")
open(OUT, "w").write("\n".join(lines) + "\n")
screen.resize((W * 4, H * 4), Image.NEAREST).save(PREVIEW)
print(f"wrote {OUT} and {PREVIEW}")
